# 🌐 Configuración del servidor
server.port=8080
#server.servlet.context-path=/

# 🧩 Información de la aplicación
spring.application.name=mongo_db_project

# 📦 Conexión a MongoDB (local o Atlas)
spring.data.mongodb.uri=${MONGODB_URI:mongodb://root:example@localhost:27017/empresa?authSource=admin}

# 🔧 Configuración de serialización JSON
spring.jackson.serialization.INDENT_OUTPUT=true

# 🧾 Configuración de Swagger / OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

# 🪵 Logging
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.com.tutorial.mongo_db_project=DEBUG

# 🔐 Seguridad básica (opcional)
#app.security.enabled=true
#app.security.default-user.username=admin
#app.security.default-user.password=admin123


